#!/bin/sh
#	Cleanup a server definition file generated by rpcgen
#
# Useage:
#	clean_server < infile > outfile
#

# Make a tmp file
#TMP=/tmp/cleanup
TMP=/tmp/cmdli-cleanup-$USER
export TMP

# sed commands to turn the old file into the new one
cat <<\xEOF > $TMP
1,$s/_._svc(/(/
1,/r2cprogram_/s/, rqstp)/)/
1,/r2cprogram_/s/(rqstp)/()/
1,$s/svc_req \*rqstp)/svc_req *)/
s/r2cprogram_1/PASCAL r2cprogram_1/
/netconfig.h/d
/\#include <rpc\/pmap_clnt.h>/c\
#ifdef linux \
#include <gssrpc/pmap_clnt.h> \
#endif
/\#include <sys\/socket.h>/c\
#ifdef linux \
#include <sys/socket.h> \
#endif
/\#include <netinet\/in.h>/c\
#ifdef linux \
#include <netinet/in.h> \
#endif
/union/c\
#ifdef WIN32 \
   gotR2Cmsg = true; \
#endif \
	union { 
xEOF
sed -f $TMP -
rm $TMP 
