#!/bin/sh
#	Cleanup a header definition file generated by rpcgen
#
# Useage:
#	clean_defs aaa 
#

# sed command to turn lowercase letters into uppercase
sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" -
