#!/bin/sh
#	Cleanup a header definition file generated by rpcgen
#
# Useage:
#	clean_xdr < infile > outfile
#

# Make a tmp file
#TMP=/tmp/cleanup
TMP=/tmp/cmdli-cleanup-$USER
export TMP

# sed commands to turn the old file into the new one
cat <<\xEOF > $TMP
#/\#include <rpc\/types.h>/\#include <rpc\/xdr.h>/c\
7,7c\
 \
#ifdef linux \
	#include <gssrpc/types.h> \
	#include <gssrpc/xdr.h> \
#else \
	#include <rpc4win.h> \
#endif \

xEOF
sed -f $TMP -
#rm $TMP 
