#!/bin/sh
#	Cleanup a client definition file generated by rpcgen
#
# Useage:
#	clean_client < infile > outfile
#

# Make a tmp file
#TMP=/tmp/cleanup
TMP=/tmp/cmdli-cleanup-$USER
export TMP

# sed commands to turn the old file into the new one
cat <<\xEOF > $TMP
1,$s/, xdr_/, (xdrproc_t)xdr_/g
1,$s/_1(/(/g
1,$s/\&,clnt_res/\&clnt_res/g
1,$s/, \&clnt_res/, (caddr_t)\&clnt_res/g
1,$s/xdr_int, \&/xdr_int, (caddr_t)\&/
1,$s/\&arg/(caddr_t)\&arg/
xEOF
sed -f $TMP -
rm $TMP 
