#!/bin/sh
#	Cleanup a header definition file generated by rpcgen
#
# Useage:
#	clean_defs < infile > outfile
#

# Make a tmp file
#TMP=/tmp/cleanup
TMP=/tmp/cmdli-cleanup-$USER
export TMP

# sed commands to turn the old file into the new one
cat <<\xEOF > $TMP
1,$s/__cplusplus/_NOT_DEFINED_/
1,$s/__STDC__/__cplusplus/
1,$s/_1_argument)/_1_argument *)/
/R2Cversion/,$s/_1(/(/
/\#include <rpc\/rpc.h>/c\
#ifdef WIN32 \
   #define RES_PARM_T (char *) \
   #define CLNT_DATA_T (char *) \
   #define SVCXPRT void \
#else \
   #include <gssrpc/rpc.h> \
   #define RES_PARM_T \
   #define CLNT_DATA_T \
#endif
xEOF
sed -f $TMP -
#rm $TMP 
