#!/bin/sh
#	Cleanup a header definition file generated by rpcgen
#
# Useage:
#	clean_defs < infile > outfile
#

# Make a tmp file
TMP=/tmp/cleanup
export TMP

# sed commands to turn the old file into the new one
cat <<\xEOF > $TMP
/\#include <unistd.h>/c\
\/*#include <unistd.h>*\/ 
xEOF
sed -f $TMP -
#rm $TMP 
